# Generated by Django 5.0.6 on 2024-07-07 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='coreapp.frame'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='coreapp.environment'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='environment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='frame',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='coreapp.entity'),
        ),
    ]
