# Generated by Django 5.0.6 on 2025-08-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='frame',
            name='coreapp_fra_entity__8479e6_idx',
        ),
        migrations.AlterField(
            model_name='frame',
            name='fnid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
