# Generated by Django 5.0.6 on 2025-08-03 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_remove_frame_coreapp_fra_entity__8479e6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='parent_frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_frames', to='coreapp.frame'),
        ),
    ]
