# Generated by Django 5.0.6 on 2024-07-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_element_frame_alter_entity_env_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='name',
            field=models.CharField(default='Entity', max_length=255),
        ),
    ]
