# Generated by Django 5.0.6 on 2025-08-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_frame_parent_frame'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frame',
            options={'ordering': ['-is_primary']},
        ),
        migrations.RemoveField(
            model_name='frame',
            name='name',
        ),
    ]
