# Generated by Django 5.0.6 on 2025-08-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_alter_frame_options_remove_frame_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='fnid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
