# Generated by Django 5.0.6 on 2025-08-05 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_alter_element_fnid'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='primary_frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_entity', to='coreapp.frame'),
        ),
    ]
